---
all:
  children:
    mm2instance00:
      hosts:
        "00.server.domain"
      vars:
        passphrase: "mm2passphrase0"
        ansible_user: ansibleuser
    mm2instance01:
      hosts:
        "01.server.domain"
      vars:
        passphrase: "mm2passphrase1"
        ansible_user: ansibleuser
    mm2instance02:
      hosts:
        "02.server.domain"
      vars:
        passphrase: "mm2passphrase2"
        ansible_user: ansibleuser
    mm2instance03:
      hosts:
        "03.server.domain"
      vars:
        passphrase: "mm2passphrase3"
        ansible_user: ansibleuser
