---
all:
  children:
    mm2instance00:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "true"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance01:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "true"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance02:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "true"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance03:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "true"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance04:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "true"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance05:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "false"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance06:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "false"
        relay_nodes: '["seed", "nodes", "array"]'
    mm2instance07:
      hosts:
        "host.ip.or.domain.name"
      vars:
        passphrase: "unique_wif"
        ansible_user: root
        relay: "false"
        relay_nodes: '["seed", "nodes", "array"]'
