---
- name: restart nginx
  become: true
  systemd:
    name: nginx
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart marketmaker2
  become: true
  systemd:
    name: marketmaker2
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart nodeexporter
  become: true
  systemd:
    name: nodeexplorer
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart filebeat
  become: true
  systemd:
    name: filebeat
    daemon_reload: true
    state: restarted
    enabled: true
